FROM ruby:3.2.2

RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && \
    apt-get update -qq && apt-get install -y \
    ca-certificates \
    curl \
    gnupg \
    build-essential \
    libpq-dev \
    postgresql-client \
    nodejs \
    libvips \
    && rm -rf /var/lib/apt/lists/*


WORKDIR /app

COPY . .