FROM ruby:3.2.2

RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && \
    apt-get update -qq && apt-get install -y \
    ca-certificates \
    curl \
    gnupg \
    build-essential \
    libpq-dev \
    nodejs \
    libvips \
    && rm -rf /var/lib/apt/lists/*


WORKDIR /app

COPY Gemfile Gemfile.lock ./
RUN bundle install

COPY package.json package-lock.json ./
RUN npm install

COPY . .

EXPOSE 3000